[package]
name = "enhvec"
version = "0.3.7"
authors = ["Mikko Tanner <mikko.tanner@gmail.com>"]
description = "Enhanced Vec with sorting and mathematics functions"
readme = "README.md"
repository = "https://github.com/Ukko-Ylijumala/enhvec-rs"
license = "MIT OR Apache-2.0"
categories = ["data-structures"]
keywords = ["vec", "mathematics"]
publish = false
edition = "2021"

[dependencies]
custom_xxh3 = { git = "https://github.com/Ukko-Ylijumala/custom_xxh3" }
